a = input('Digite algo:')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços ?', a.isspace())
print('É um número ?', a.isnumeric())
print('É alfabetico ?', a.isalnum())
print('É alfanumerico ?', a.isalpha())
print('É maiusculo ?', a.isupper())
print('É minusculo ?', a.islower())
print('Está capitalizada ?:', a.istitle())